---
title: "Resume"
output:
  html_document:
    toc: yes
pagetitle: Resume
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Sabrina Strausser

Address  2400 Nueces St
	       Apartment #1341
	       Austin, Texas
	       78705

Phone  936-520-2977

Email  sabrina.strausser@gmail.com 

Education

2020			Bachelor of Science, Biology
			The University of Texas, Austin, TX

			Relevant coursework:
			- Biology
			- Biochemistry
			- General Chemistry 	
			- Organic Chemistry
			- Physics
			- Calculus
			- Genetics
			- Human Genetics 
			- Peer mentor for Gene Detectives Course (Spring Semester 2017)
			- Peer mentor for Introduction to Computational Biology Course (Fall Semester 2017)		

Medical and Research Experience

2015 - 2016 		AMSA
			- Active member of the American Medical Students Association at UT

2015 - 2017		Freshman Research Initiative at UT
			- Freshman Research Initiative Undergraduate Researcher (Fall Semester 					  2015, Spring Semester 2016)
			- Freshman Research Initiative Peer Mentor (Spring Semester 2017, Fall Semester 2017)

2016 - 2018		Physician Shadowing Experiences
			- Dr. David Strausser - Observation of spine surgery at First Surgical 					  Surgery Center (June 2016)
			- Dr. Alfonso Barrera - Observation of facelift and blepharoplasty at West 					   Houston Plastic Surgery Clinic (August 2016)
			- Dr. Alfonso Barrera - Observation of facelift, blepharoplasty, and 						   liposuction of the back at West Houston Plastic Surgery Clinic (January 					   2017)
			- Dr. Jack Pieniazek, Dr. Samson Sheih - Shadowing experience at Conroe 			   Family Medicine (Spring 2018)

Volunteer Work

2015 - 2019		Street Youth Ministry Food Recovery Helper 	

2015 - 2016		AMSA Volunteer
			- Capital Area Food Bank of Texas
			- The Leukemia & Lymphoma Society’s Light the Night Walk
			- The JDRF One Walk
			- The Q Austin